[tools]
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
selene = "kampfkarren/selene@0.27.1"
rojo = "rojo-rbx/rojo@7.4.2"
luau-lsp = "JohnnyMorganz/luau-lsp@1.32.1"
stylua = "JohnnyMorganz/StyLua@0.20.0"
pseudo-enum = "nightcycle/pseudo-enum@0.2.3"
file-to-luau = "nightcycle/file-to-luau@1.0.0"
file-util = "nightcycle/file-util@0.1.2"