--!strict
-- this script is auto generated, don't manually change it please
return {
	["home"] = {
		["Image"] = "rbxassetid://15529284152",
		["ImageRectOffset"] = Vector2.new(0, 0),
		["ImageRectSize"] = Vector2.new(72, 72),
	},
	["info_outline"] = {
		["Image"] = "rbxassetid://15529284152",
		["ImageRectOffset"] = Vector2.new(72, 0),
		["ImageRectSize"] = Vector2.new(72, 72),
	},
	["fiber_manual_record"] = {
		["Image"] = "rbxassetid://15529284152",
		["ImageRectOffset"] = Vector2.new(144, 0),
		["ImageRectSize"] = Vector2.new(72, 72),
	},
	["speaker"] = {
		["Image"] = "rbxassetid://15529284152",
		["ImageRectOffset"] = Vector2.new(216, 0),
		["ImageRectSize"] = Vector2.new(72, 72),
	},
	["tv"] = {
		["Image"] = "rbxassetid://15529284152",
		["ImageRectOffset"] = Vector2.new(288, 0),
		["ImageRectSize"] = Vector2.new(72, 72),
	},
	["domain"] = {
		["Image"] = "rbxassetid://15529284152",
		["ImageRectOffset"] = Vector2.new(360, 0),
		["ImageRectSize"] = Vector2.new(72, 72),
	},
	["person_add"] = {
		["Image"] = "rbxassetid://15529284152",
		["ImageRectOffset"] = Vector2.new(432, 0),
		["ImageRectSize"] = Vector2.new(72, 72),
	},
}