--!strict
-- this script is auto generated, don't manually change it please
return {
	["home"] = {
		["Image"] = "rbxassetid://15530163086",
		["ImageRectOffset"] = Vector2.new(0, 0),
		["ImageRectSize"] = Vector2.new(144, 144),
	},
	["info_outline"] = {
		["Image"] = "rbxassetid://15530163086",
		["ImageRectOffset"] = Vector2.new(144, 0),
		["ImageRectSize"] = Vector2.new(144, 144),
	},
	["fiber_manual_record"] = {
		["Image"] = "rbxassetid://15530163086",
		["ImageRectOffset"] = Vector2.new(288, 0),
		["ImageRectSize"] = Vector2.new(144, 144),
	},
	["speaker"] = {
		["Image"] = "rbxassetid://15530163086",
		["ImageRectOffset"] = Vector2.new(432, 0),
		["ImageRectSize"] = Vector2.new(144, 144),
	},
	["tv"] = {
		["Image"] = "rbxassetid://15530163086",
		["ImageRectOffset"] = Vector2.new(576, 0),
		["ImageRectSize"] = Vector2.new(144, 144),
	},
	["domain"] = {
		["Image"] = "rbxassetid://15530163086",
		["ImageRectOffset"] = Vector2.new(720, 0),
		["ImageRectSize"] = Vector2.new(144, 144),
	},
	["person_add"] = {
		["Image"] = "rbxassetid://15530163086",
		["ImageRectOffset"] = Vector2.new(864, 0),
		["ImageRectSize"] = Vector2.new(144, 144),
	},
}