--!strict
-- this script is auto generated, don't manually change it please
return {
	["home"] = {
		["Image"] = "rbxassetid://15529288695",
		["ImageRectOffset"] = Vector2.new(0, 0),
		["ImageRectSize"] = Vector2.new(108, 108),
	},
	["info_outline"] = {
		["Image"] = "rbxassetid://15529288695",
		["ImageRectOffset"] = Vector2.new(108, 0),
		["ImageRectSize"] = Vector2.new(108, 108),
	},
	["fiber_manual_record"] = {
		["Image"] = "rbxassetid://15529288695",
		["ImageRectOffset"] = Vector2.new(216, 0),
		["ImageRectSize"] = Vector2.new(108, 108),
	},
	["speaker"] = {
		["Image"] = "rbxassetid://15529288695",
		["ImageRectOffset"] = Vector2.new(324, 0),
		["ImageRectSize"] = Vector2.new(108, 108),
	},
	["tv"] = {
		["Image"] = "rbxassetid://15529288695",
		["ImageRectOffset"] = Vector2.new(432, 0),
		["ImageRectSize"] = Vector2.new(108, 108),
	},
	["domain"] = {
		["Image"] = "rbxassetid://15529288695",
		["ImageRectOffset"] = Vector2.new(540, 0),
		["ImageRectSize"] = Vector2.new(108, 108),
	},
	["person_add"] = {
		["Image"] = "rbxassetid://15529288695",
		["ImageRectOffset"] = Vector2.new(648, 0),
		["ImageRectSize"] = Vector2.new(108, 108),
	},
}