--!strict
-- this script is auto generated, don't manually change it please
return {
	["home"] = {
		["Image"] = "rbxassetid://15530150895",
		["ImageRectOffset"] = Vector2.new(0, 0),
		["ImageRectSize"] = Vector2.new(54, 54),
	},
	["info_outline"] = {
		["Image"] = "rbxassetid://15530150895",
		["ImageRectOffset"] = Vector2.new(54, 0),
		["ImageRectSize"] = Vector2.new(54, 54),
	},
	["fiber_manual_record"] = {
		["Image"] = "rbxassetid://15530150895",
		["ImageRectOffset"] = Vector2.new(108, 0),
		["ImageRectSize"] = Vector2.new(54, 54),
	},
	["speaker"] = {
		["Image"] = "rbxassetid://15530150895",
		["ImageRectOffset"] = Vector2.new(162, 0),
		["ImageRectSize"] = Vector2.new(54, 54),
	},
	["tv"] = {
		["Image"] = "rbxassetid://15530150895",
		["ImageRectOffset"] = Vector2.new(216, 0),
		["ImageRectSize"] = Vector2.new(54, 54),
	},
	["domain"] = {
		["Image"] = "rbxassetid://15530150895",
		["ImageRectOffset"] = Vector2.new(270, 0),
		["ImageRectSize"] = Vector2.new(54, 54),
	},
	["person_add"] = {
		["Image"] = "rbxassetid://15530150895",
		["ImageRectOffset"] = Vector2.new(324, 0),
		["ImageRectSize"] = Vector2.new(54, 54),
	},
}