--!strict
-- search for icons here: https://fonts.google.com/icons
-- this script is auto generated, don't manually change it please
return {
	["default"] = {
		["dp_18"] = {
			["scale_1"] = require(script:WaitForChild("Default_18_1")),
			["scale_2"] = require(script:WaitForChild("Default_18_2")),
			["scale_3"] = require(script:WaitForChild("Default_18_3")),
			["scale_4"] = require(script:WaitForChild("Default_18_4")),
		},
		["dp_24"] = {
			["scale_1"] = require(script:WaitForChild("Default_24_1")),
			["scale_2"] = require(script:WaitForChild("Default_24_2")),
			["scale_3"] = require(script:WaitForChild("Default_24_3")),
			["scale_4"] = require(script:WaitForChild("Default_24_4")),
		},
		["dp_36"] = {
			["scale_1"] = require(script:WaitForChild("Default_36_1")),
			["scale_2"] = require(script:WaitForChild("Default_36_2")),
			["scale_3"] = require(script:WaitForChild("Default_36_3")),
			["scale_4"] = require(script:WaitForChild("Default_36_4")),
		},
		["dp_48"] = {
			["scale_1"] = require(script:WaitForChild("Default_48_1")),
			["scale_2"] = require(script:WaitForChild("Default_48_2")),
			["scale_3"] = require(script:WaitForChild("Default_48_3")),
			["scale_4"] = require(script:WaitForChild("Default_48_4")),
		},
	},
	["outlined"] = {
		["dp_18"] = {
			["scale_1"] = require(script:WaitForChild("Outlined_18_1")),
			["scale_2"] = require(script:WaitForChild("Outlined_18_2")),
		},
		["dp_24"] = {
			["scale_1"] = require(script:WaitForChild("Outlined_24_1")),
			["scale_2"] = require(script:WaitForChild("Outlined_24_2")),
		},
		["dp_36"] = {
			["scale_1"] = require(script:WaitForChild("Outlined_36_1")),
			["scale_2"] = require(script:WaitForChild("Outlined_36_2")),
		},
		["dp_48"] = {
			["scale_1"] = require(script:WaitForChild("Outlined_48_1")),
			["scale_2"] = require(script:WaitForChild("Outlined_48_2")),
		},
	},
	["round"] = {
		["dp_18"] = {
			["scale_1"] = require(script:WaitForChild("Round_18_1")),
			["scale_2"] = require(script:WaitForChild("Round_18_2")),
		},
		["dp_24"] = {
			["scale_1"] = require(script:WaitForChild("Round_24_1")),
			["scale_2"] = require(script:WaitForChild("Round_24_2")),
		},
		["dp_36"] = {
			["scale_1"] = require(script:WaitForChild("Round_36_1")),
			["scale_2"] = require(script:WaitForChild("Round_36_2")),
		},
		["dp_48"] = {
			["scale_1"] = require(script:WaitForChild("Round_48_1")),
			["scale_2"] = require(script:WaitForChild("Round_48_2")),
		},
	},
	["sharp"] = {
		["dp_18"] = {
			["scale_1"] = require(script:WaitForChild("Sharp_18_1")),
			["scale_2"] = require(script:WaitForChild("Sharp_18_2")),
		},
		["dp_24"] = {
			["scale_1"] = require(script:WaitForChild("Sharp_24_1")),
			["scale_2"] = require(script:WaitForChild("Sharp_24_2")),
		},
		["dp_36"] = {
			["scale_1"] = require(script:WaitForChild("Sharp_36_1")),
			["scale_2"] = require(script:WaitForChild("Sharp_36_2")),
		},
		["dp_48"] = {
			["scale_1"] = require(script:WaitForChild("Sharp_48_1")),
			["scale_2"] = require(script:WaitForChild("Sharp_48_2")),
		},
	},
	["two_tone"] = {
		["dp_18"] = {
			["scale_1"] = require(script:WaitForChild("TwoTone_18_1")),
			["scale_2"] = require(script:WaitForChild("TwoTone_18_2")),
		},
		["dp_24"] = {
			["scale_1"] = require(script:WaitForChild("TwoTone_24_1")),
			["scale_2"] = require(script:WaitForChild("TwoTone_24_2")),
		},
		["dp_36"] = {
			["scale_1"] = require(script:WaitForChild("TwoTone_36_1")),
			["scale_2"] = require(script:WaitForChild("TwoTone_36_2")),
		},
		["dp_48"] = {
			["scale_1"] = require(script:WaitForChild("TwoTone_48_1")),
			["scale_2"] = require(script:WaitForChild("TwoTone_48_2")),
		},
	},
}